# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

		before_all do |lane, options|
			APP_ID = options[:APP_ID]
			puts "Valeur de APP_ID: #{APP_ID}"
			FIREBASE_CLI_TOKEN = options[:FIREBASE_CLI_TOKEN]
			puts "Valeur de FIREBASE_CLI_TOKEN: #{FIREBASE_CLI_TOKEN}"
			TESTERS = options[:TESTERS]
			puts "Valeur de TESTERS: #{TESTERS}"
			ARTIFACT_PATH = options[:ARTIFACT_PATH]
			puts "Valeur de ARTIFACT_PATH: #{ARTIFACT_PATH}"
		end
			
			
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end
  
  desc "Build The APK of the app"
  lane :build do
	gradle(task: "clean assembleRelease")
  end

	desc "Deploy to firebase App Distribution"
	lane :distribute do |options|
	
			firebase_app_distribution(
			app: "#{APP_ID}",
			firebase_cli_token: "#{FIREBASE_CLI_TOKEN}",
			android_artifact_type: "APK",
			android_artifact_path: "#{ARTIFACT_PATH}",
            testers: "#{TESTERS}",
            release_notes: "Lots of amazing new features to test out!"
        )
	end
	
end